name: Test django on Issue branch

on:
  push:
    branches:
      - Issue-*
    paths:
      - .github/workflows/test-django-issues.yml
      - django/Pipfile.lock
      - django/src/**

jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      WORKDIR: ./django

    steps:
      - uses: actions/checkout@v2

      - name: Build docker image for test
        run:  docker build -t test --target=test .
        working-directory: ${{ env.WORKDIR }}

      - name: Run MySQL
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose up -d
        working-directory: ${{ env.WORKDIR }}

      - name: Migrate database
        run: |
          docker run \
            -e BYFS_LOCAL_DB_HOST \
            -it \
            --network django_sppl \
            --rm \
            test \
            ./manage.py makemigrations && \
            ./manage.py migrate
        env:
          BYFS_LOCAL_DB_HOST: mysql

      - name: Run test
        run: |
          docker run \
            -e BYFS_LOCAL_DB_HOST \
            -it \
            --network django_sppl \
            --rm \
            test
        env:
          BYFS_LOCAL_DB_HOST: mysql

      - name: Clean
        if: always()
        run: |
          docker-compose down
