name: Test django on Issue branch

on:
  push:
    branches:
      - Issue-*
    paths:
      - .github/workflows/test-django-issues.yml
      - django/Pipfile.lock
      - django/src/**

jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      WORKDIR: ./django

    steps:
      - uses: actions/checkout@v2

      - name: Install python packages
        run: |
          # install python 3.8
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get update -y
          sudo apt-get install -y python3.8
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2
          sudo update-alternatives --config python3
          python3 --version
          # install pip3
          sudo apt install python3-pip
          # install pipenv and packages
          python3 -m pip install --user pipenv
          pipenv install --system --deploy --clear

      - name: Run MySQL
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose up -d
        working-directory: ${{ env.WORKDIR }}

      - name: Run test
        run: |
          ./src/manage.py test
        working-directory: ${{ env.WORKDIR }}

      - name: Clean
        if: always()
        run: |
          docker-compose down
