name: Test django on Issue branch

on:
  push:
    branches:
      - Issue-*
    paths:
      - .github/workflows/test-django-issues.yml
      - django/Pipfile.lock
      - django/src/**

jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      WORKDIR: ./django

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          pipenv install --system --deploy --clear

      - name: Initialize test environment
        id: docker
        run: |
          docker-compose up -d
        working-directory: ${{ env.WORKDIR }}

      - name: Run test
        run: |
          ./src/manage.py test
        working-directory: ${{ env.WORKDIR }}

      - name: Clean
        if: always()
        run: |
          docker-compose down
